name: IQ Evaluation
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn dependency:copy-dependencies

    - name: Lifecycle Policy Evaluation
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: ${{ vars.LIFECYCLE_SERVER }}
        username: ${{ secrets.LIFECYCLE_USERNAME }}
        password: ${{ secrets.LIFECYCLE_PASSWORD }}
        application-id: ${{ github.event.repository.name }}
        scan-targets: target/**/*.jar
